services:
   postgres-workerbench:
     image: dpage/pgadmin4:latest
     env_file:
       - .env
     environment:
       - PGADMIN_DEFAULT_EMAIL
       - PGADMIN_DEFAULT_PASSWORD
       - TZ
     ports:
         - "8081:80"

     volumes:
       - ./pgadmin-data:/var/lib/pgadmin
     networks:
            - postgres-network
     restart: unless-stopped

   postgres-db:
     image: postgres:latest
     env_file:
       - .env
     environment:
       - POSTGRES_USER
       - POSTGRES_PASSWORD
       - TZ
     ports:
       - "5433:5432"
     volumes:
       - ./postgres-data:/var/lib/postgresql/data
     networks:
         - postgres-network
     restart: unless-stopped
   # #  # Spring Boot Application

   app:
      build:
        context: .
        dockerfile: Dockerfile
      image: samuelfamilia/spring-movie
      container_name: cont-spring-movie
      depends_on:
        - postgres-db
      env_file:
        - .env
      ports:
        - "8080:8080"
      networks:
        - postgres-network
      volumes:
            - ./logs:/logs
      restart: unless-stopped
networks:
    postgres-network:
        driver: bridge
